name: Build and Publish package
on:
  push:
    branches: [ master ]

jobs:
  build-publish-package:
    name: Build and Publish package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
          server-id: nexus-sonatype
          server-username: NEXUS_USERNAME
          server-password: NEXUS_PASSWORD
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_MVN_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.S3_MVN_SECRET_KEY }}
          aws-region: ap-southeast-1
      - name: Build and deploy with Maven
        run: ./mvnw --no-transfer-progress clean -U deploy
        env:
          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
